# Generated by Django 3.0.5 on 2020-05-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
